In [1]:
import numpy as np
from IPython.display import display


In [2]:
#1
num= np.arange(18, 54)
print(num)

[18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
 42 43 44 45 46 47 48 49 50 51 52 53]


In [16]:
#2
num_c=num.reshape(-1, 6) 
print(num_c)

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]]


In [21]:
#3
print(num_c[3][3])

39


In [28]:
#4
17+39
#לא

56

In [29]:
'''תרגיל 2'''
#1
np.random.seed(42)
rand_array = np.random.randint(0, 101, (5, 5))
print(rand_array)
max_num = rand_array.max()
a = max_num / 2+7
print(a)
#לא

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
56.5
